config/routes.rb
Rails.application.routes.draw do
  get 'trade_request/:id' => 'trade#trade_request', as: 'trade_request'
  get 'incoming_trade_request' => 'trade#incoming_trade_request', as: 'incoming_trade_request'
  get 'pending_request' => 'trade#pending_request', as: 'pending_request'
  post '/accept_shift/:id', to:'trade#accept_shift', as: 'accept_shift'
  delete '/decline_shift/:id', to:'trade#decline_shift', as: 'decline_shift'
 resources :trade_request,  :except => [:index, :new, :update, :create, :destroy, :edit, :show] do
   member do
     put '' => 'trade#send_request'
     patch '' => 'trade#send_request'
  end
 end
  

 
 

  get 'shift_trade_board' => 'posted_shift#index', as: 'shift_trade_board'
  post 'post_shift/:id' => 'posted_shift#post_shift', as: 'post_shift' 
  post '/cancel_shift/:id', to:'posted_shift#cancel_shift', as: 'cancel_shift'
  post '/pick_up_shift/:id/pickup', to:'posted_shift#pick_up_shift', as: 'pick_up_shift'
  resources :shifts

  get 'calendar' => 'calendar#index', as:'calendar'

  devise_for :users
  root 'staticpages#home'

end

app/models/shift.rb
class Shift < ActiveRecord::Base
    belongs_to :user
    
     include Workflow
    
    workflow do
        state :new do
            event :post, :transitions_to => :posted
            event :trade_request, :transitions_to => :pending_request
            
        end
        
        state :posted do
            event :sold, :transitions_to => :traded
            event :cancel, :transitions_to => :new
            event :trade_request, :transitions_to => :pending_request
        end
        
        state :pending_request do 
           event :accept, :transitions_to => :traded
           event :decline, :transitions_to => :new
        end
        state :traded do 
            event :post, :transitions_to => :posted
            event :trade_request, :transitions_to => :pending_request
        end
    end
    
    def calendar_start_time
        start.change(day: date.day, month: date.month, year: date.year)
    end
    
    def calendar_end_time
        finish.change(day: date.day, month: date.month, year: date.year)
    end
    
    
    def overlaps?(shift)
        (start - shift.finish) * (shift.start - finish) > 0
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :shifts

  def available?(trade_shift)
        @shift = self.shifts.where(date: trade_shift.date).first
        if !@shift.nil?
            if @shift.overlaps?(trade_shift)
                return false
            else
                return true
            end
        else 
            return true
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :authenticate_user!
  def index
    @shift = Shift.new
  end
end

app/controllers/posted_shift_controller.rb
class PostedShiftController < ApplicationController
   before_action :authenticate_user!
   before_action :set_shift, only: [:cancel_shift, :pick_up_shift, :post_shift]
   
  def index
    @shifts = Shift.with_posted_state.includes(:user)
    
  end
  
  def post_shift
    if !@shift.posted?
        flash[:notice] = 'Shift successfully Posted.' if @shift.post!
        redirect_to shift_trade_board_path
    else
        flash[:alert] = 'Shift already on Trade Board!'
        redirect_to @shift
    end
  end
  
  def cancel_shift

     flash[:notice] = 'Shift successfully removed from board.' if @shift.cancel!
     redirect_to shift_trade_board_path
  end
  
  def pick_up_shift
    
    if current_user.available?(@shift)
        @user_shift = @shift
        @user_shift.user_id = current_user.id
        
        if @shift.save && @shift.sold!
            flash[:notice] = 'Shift successfully traded.' 
            redirect_to calendar_path
        else
            flash[:alert] = "Shift Could not be Traded"
             redirect_to shift_trade_board_path
        end
    else
        flash[:alert] = "#{current_user.email} are already working that day."
        redirect_to shift_trade_board_path
    end
    
  end
  
   private
    def set_shift
      @shift = Shift.find(params[:id])
    end
  
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @shifts =current_user.shifts
    respond_with(@shifts)
  end

  def show
    respond_with(@shift)
  end

  def new
    @date_example = Date.today
    @shift = Shift.new
    respond_with(@shift)
  end

  def edit
  end

  def create
    @shift = Shift.new(shift_params)
    @shift.original_owner = @shift.user_id = current_user.id
    @shift.save
    respond_with(@shift, :location => calendar_path)
  end

  def update
    @shift.update(shift_params)
    respond_with(@shift)
  end

  def destroy
    @shift.destroy
    respond_with(@shift)
  end

  private
    def set_shift
      @shift = Shift.find(params[:id])
    end

    def shift_params
      params.require(:shift).permit(:position, :date, :start, :finish, :description, :workflow_state, :shift_type)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/controllers/trade_controller.rb
class TradeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shift, only: [:trade_request, :send_request, :accept_shift, :decline_shift]
  
  def trade_request
   
  end
  
  def send_request
    @user_shift = User.find(params[:shift][:tr_user_id])
    if @user_shift.available?(@shift)
        if @shift.update(shift_params) && @shift.trade_request!
        flash[:notice] = 'Trade request succesfully sent to #{@user.email}'
        redirect_to calendar_path
        else 
        flash[:alert] = 'Request could not be sent!'
        redirect_to @shift
        end
       
    else
    
      flash[:alert] = 'This collegue is unable to work of you.'
      redirect_to trade_request_path
    end
  
  end
  
  def pending_request
     @shifts = current_user.shifts.with_pending_request_state
  end
  
  def incoming_trade_request
    @shifts = Shift.with_pending_request_state.where(tr_user_id: current_user.id)
  end
  
  
  def accept_shift
    
    if current_user.available?(@shift)
        @user_shift = @shift
        @user_shift.user_id = current_user.id
        @user_shift.tr_user_id = nil
        
        if @shift.save && @shift.accept!
            flash[:notice] = 'Shift successfully traded.' 
            redirect_to calendar_path
        else
            flash[:alert] = "Shift Could not be Traded"
             redirect_to incoming_trade_request_path
        end
        
    else
        flash[:alert] = "#{current_user.email} are already working that day."
        redirect_to shift_trade_board_path
    end
    
  end
  
  def decline_shift
    @shift.tr_user_id = nil
    flash[:notice] = 'Request successfully declined.' if @shift.save && @shift.decline!
    redirect_to pending_request_path

  end
  
  private
  
    def set_shift
      @shift = Shift.find(params[:id])
    end
    
    def shift_params
      params.require(:shift).permit(:position, :date, :start, :finish, :description, :workflow_state, :tr_user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/posted_shift_helper.rb
module PostedShiftHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/trade_helper.rb
module TradeHelper
end

app/views/calendar/index.html.erb
<div id="calendar">
    
</div>

<%= link_to 'New Shift', new_shift_path, :class => 'btn btn-default' %>

app/views/layouts/_userlayout.html.erb
<%- #------------Side Bar--------------%> 
<div class="col-sm-3 col-md-3">
    
    
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                            </span>Air Canada</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span><a href="https://acaeronet.aircanada.ca">Aeronet</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-flash text-success"></span><a href="http://yyzdistrict301.com">Unifor</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                                        <span class="badge">42</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Change Password</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Import/Export</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                                            Delete Account</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                            </span>Reports</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
                <% if current_page?(:controller => 'calendar') %>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive"><span class="glyphicon glyphicon-file">
                            </span>Add A New Shift</a>
                        </h4>
                    </div>
                    <div id="collapseFive" class="panel-collapse collapse">
                        <div class="panel-body">
                            <%= render 'shifts/form2' %>
                        </div>
                    </div>
                </div>
                <% end %>
          
        </div>
<%- #-------------END Side Bar ----------------%>
        <div class="col-sm-9 col-md-9">
              <%= yield %>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ESTC</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Trade Center<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Trade Board', shift_trade_board_path %></li>
                <li><%= link_to 'Trade Request', incoming_trade_request_path %></li>
                <li><%= link_to 'Pending Request', pending_request_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
             
             <% if signed_in? %>
                <li><%= link_to 'Calendar', calendar_path, method: :get %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <%else%>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to'Register', new_user_registration_path %></li>
            <%end%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <% flash.each do |message_type, message| %>
        <div class="alert-box <%= message_type %> radius"><%= message %><div class="close_box">X</div></div>
    <% end %>
<div class="container" >
  <% if signed_in? %>
    <%= render '/layouts/userlayout' %>
  <% else %>
    <%= yield %>
  <% end %>
</div>


</body>
</html>

app/views/posted_shift/index.html.erb
<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Trade Board List</div>
		<div class="panel-body">
			<p>The following list container shift that your collegue wishe to give away. Click 'Pick Up', if you can help them. </p>
</div>
<table class="table custom_table table-striped table-hover table-condensed">

        <thead>

            <tr>

                <th>Email</th>
                
                <th>Position</th>
                
                <th>Date</th>

                <th>Start</th>
                
                <th>End</th>
                <th>Description</th>
                <th> </th>

            </tr>

        </thead>

        <tbody>
            <% @shifts.each do |shift| %>
            <tr>

                <td><%= shift.user.email %></td>
                <td><%= shift.position %></td>
                <td><%= shift.date.to_date.to_s(:long)%></td>

                <td><%= shift.start.to_s(:time)%></td>
                <td><%= shift.finish.to_s(:time)%></td>
                <td><%= shift.description %></td>
                <% if shift.user_id == current_user.id %>
                    <td><%= link_to 'Remove', cancel_shift_path(shift), method: :post %></td>
                <% else %>
                    <td><%= link_to 'Pick Up', pick_up_shift_path(shift), method: :post %></td>
                <% end %>

            </tr>

           <% end %>
            
        </tbody>
      
    </table>

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.error_notification %>

    <div class="row">
      <div class="col-sm-2">
      <%= f.input :position, as: :select, collection:['Zone 5 Gates','Zone 1 Gates','Zone 3 Gates','Zone 4 Gates', ] %>
      </div>
    </div>
    
     <div class="row">
      <div class="col-sm-2">
        <%= f.input :date, as: :string, placeholder: 'January 15, 2015' %>
         </div>
    </div>
    
    <div class="row">
      <div class="col-sm-2 inline">
        <%= f.input :start, as: :time,as: :string, placeholder:"hrs:mins"  %>
        </div>
    </div>
    
    <div class="row">
      <div class="col-sm-2 inline">
        <%= f.input :finish, as: :time,as: :string, placeholder:"hrs:mins" %>
        </div>
    </div>
    
     <div class="row">
      <div class="col-sm-3 inline">
        <%= f.input :description %>
      </div>
    </div>
    
  

   <div class="row">
    <div class="col-sm-3 inline">
      <%= f.button :submit %>
      </div>
    </div>
  

  <% end %>

app/views/shifts/_form2.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.error_notification %>

    <div class="row">
      <div class="col-sm-12">
      <%= f.input :position, as: :select, collection:['Zone 5 Gates','Zone 1 Gates','Zone 3 Gates','Zone 4 Gates', ] %>
      </div>
    </div>
    
     <div class="row">
      <div class="col-sm-12">
        <%= f.input :date, as: :string, placeholder: 'January 15, 2015' %>
         </div>
    </div>
    
    <div class="row">
      <div class="col-sm-12 inline">
        <%= f.input :start, as: :time,as: :string, placeholder:"hrs:mins"  %>
        </div>
    </div>
    
    <div class="row">
      <div class="col-sm-12 inline">
        <%= f.input :finish, as: :time,as: :string, placeholder:"hrs:mins" %>
        </div>
    </div>
    
     <div class="row">
      <div class="col-sm-12 inline">
        <%= f.input :description %>
      </div>
    </div>
    
  

   <div class="row">
    <div class="col-sm-12 inline">
      <%= f.button :submit %>
      </div>
    </div>
  

  <% end %>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render 'form' %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h1>Listing shifts</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Date</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Description</th>
      <th>Workflow state</th>
      <th>Shift type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.position %></td>
        <td><%= shift.date %></td>
        <td><%= shift.start %></td>
        <td><%= shift.finish %></td>
        <td><%= shift.description %></td>
        <td><%= shift.workflow_state %></td>
        <td><%= shift.shift_type %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<div class="container">
<h1>New shift</h1>

<%= render 'form' %>

<%= link_to 'Back', shifts_path %>
</div>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @shift.position %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shift.date.to_date.to_s(:long) %>
</p>

<p>
  <strong>Start:</strong>
  <%= @shift.start.to_s(:time) %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @shift.finish.to_s(:time) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shift.description %>
</p>



<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %> 
<% if !@shift.posted? %>
  | <%= link_to 'Post Shift',post_shift_path(@shift) ,method: :post %> 
<% end %>
<% if !@shift.pending_request? %>
  | <%= link_to 'Trade With A Collegue', trade_request_path(@shift)%>
<% end %>

app/views/staticpages/home.html.erb
<h1>Staticpages#home</h1>
<p>Find me in app/views/staticpages/home.html.erb</p>

app/views/trade/_form.html.erb
<%= simple_form_for @shift, url: trade_request_path do |f| %>
  <%= f.error_notification %>

    <div class="row">
      <div class="col-sm-2">
      <%= f.input :position, as: :string, input_html: {:value => f.object.position}, disabled: true%>
      </div>
    </div>
    
     <div class="row">
      <div class="col-sm-2">
        <%= f.input :date, as: :string, placeholder: 'January 15, 2015', input_html: { :value => f.object.date.to_date.to_s(:long) }, disabled: true %>
         </div>
    </div>
    
    <div class="row">
      <div class="col-sm-2 inline">
        <%= f.input :start, as: :time,as: :string, placeholder:"hrs:mins", input_html: { :value => f.object.start.to_s(:time) } %>
        </div>
    </div>
    
    <div class="row">
      <div class="col-sm-2 inline">
        <%= f.input :finish, as: :time,as: :string, placeholder:"hrs:mins", input_html: { :value => f.object.finish.to_s(:time) } %>
        </div>
    </div>
    
     <div class="row">
      <div class="col-sm-3 inline">
        <%= f.input :description %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-sm-2 inline">
        <%= f.input :tr_user_id, placeholder: 'Select A Collegue', collection: User.all.where.not(id: current_user.id).collect{|u| [u.email, u.id]}, :prompt => 'Select' , default: 1, label: false  %>
      </div>
    </div>

   <div class="row">
    <div class="col-sm-3 inline">
      <%= f.button :submit %>
      </div>
    </div>
  

  <% end %>

app/views/trade/incoming_trade_request.html.erb
<table class="table table-striped table-hover table-bordered">

        <thead>

            <tr>

                <th>Email</th>
                
                <th>Position</th>
                
                <th>Date</th>

                <th>Start</th>
                
                <th>End</th>
                <th>Description</th>

            </tr>

        </thead>

        <tbody>
            <% @shifts.each do |shift| %>
            <tr>

                <td><%= shift.user.email %></td>
                <td><%= shift.position %></td>
                <td><%= shift.date.to_date.to_s(:long)%></td>

                <td><%= shift.start.to_s(:time)%></td>
                <td><%= shift.finish.to_s(:time)%></td>
                <td><%= shift.description %></td>
                <td><%= link_to 'Accept',  accept_shift_path(shift), method: :post %></td>
                <td><%= link_to 'Decline' %></td>

            </tr>

           <% end %>
            
        </tbody>
      
    </table>

app/views/trade/pending_request.html.erb
    <div class="method">
        <div class="row margin-0 list-header hidden-sm hidden-xs">
            <div class="col-md-3"><div class="header">Email</div></div>
            <div class="col-md-2"><div class="header">Position</div></div>
            <div class="col-md-2"><div class="header">Date</div></div>
            <div class="col-md-2"><div class="header">start-end</div></div>
            <div class="col-md-3"><div class="header">Description</div></div>
        </div>
        
        <% @shifts.each do |shift| %>
           
        <div class="row margin-0">
            <div class="col-md-3">
                <div class="cell">
                    <div class="propertyname">
                         <%= shift.user.email %>  <span class="mobile-isrequired">[Required]</span>
                    </div>
                </div>
            </div>
            
            <div class="col-md-2">
                <div class="cell">
                    <div class="type">
                       <%= shift.position %> <span class="mobile-isrequired">[Required]</span>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="cell">
                    <div class="type">
                       <%= shift.date.to_date.to_s(:long) %> <span class="mobile-isrequired">[Required]</span>
                    </div>
                </div>
            </div>
            
            <div class="col-md-2">
                <div class="cell">
                    <div class="type">
                       <%= "#{shift.start.to_s(:time)} - #{shift.finish.to_s(:time)}" %> <span class="mobile-isrequired">[Required]</span>
                    </div>
                </div>
            </div>
            
            <div class="col-md-3">
                <div class="cell">
                    <div class="description">
                        <%= shift.description %>
                    </div>
                </div>
            </div>
        </div>
      <% end %>
      
        </div>

app/views/trade/trade_request.html.erb
<h1>Trade#trade_requests</h1>
<%= render 'form' %>